name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened]
jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        if: github.actor != 'scylladbbot'
        uses: technote-space/assign-author@v1
