name: Check if commits are promoted

on:
  push:
    branches:
      - master
      - branch-*.*

env:
  DEFAULT_BRANCH: "master"

jobs:
  check-commit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.DEFAULT_BRANCH }}
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-github
          python -m pip install --upgrade pip
          pip install gitpython requests

      - name: Run python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python auto-backport.py
