name: Rebase PR on Mention

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@yaronkaikov rebase')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched for rebasing

      - name: Get Pull Request Details
        id: pr-details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract PR Details
        id: extract-pr
        run: |
          echo "${{ steps.pr-details.outputs.data }} | jq -r '.pull_request.head.ref'"
          echo "${{ steps.pr-details.outputs.data }} | jq -r '.pull_request.base.ref')"
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Rebase Pull Request
        run: |
          git checkout $PR_BRANCH
          git rebase origin/$TARGET_BRANCH

      - name: Push Rebasing Changes
        run: |
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
