name: Rebase PR on Mention

on:
  issue_comment:
    types:
      - created

jobs:
  rebase:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@yaronkaikov')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched for rebasing

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Rebase Pull Request
        run: |
          PR_BRANCH=$(echo ${{ github.event.issue.pull_request.head.ref }})
          TARGET_BRANCH=$(echo ${{ github.event.issue.pull_request.base.ref }})
          git checkout $PR_BRANCH
          git rebase origin/$TARGET_BRANCH

      - name: Push Rebasing Changes
        run: |
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
